AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Globals:
  Function:
    Timeout: 3

Parameters:
  UrlToDownload:
    Type: String
    Default: https://my.better.example.url
    Description: URL to download

Resources:
  HelloWorldBucket:
    Type: AWS::S3::Bucket
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Policies:
        - S3WritePolicy:
            BucketName:
              Ref: HelloWorldBucket
      Environment:
        Variables:
          DOWNLOADURL:
            Ref: UrlToDownload
          BUCKETNAME:
            Ref: HelloWorldBucket
          KEYNAME: "MyKey"

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
